### ISSUE TITLE
instance system.adapter.husq-automower.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

### ISSUE THREAD

**Issue by Stefan-83** [truegreyhound/ioBroker.husq-automower#22]
Hi,
I've insert my account data (email & password), but the adapter isn't working.
Any ideas?
Thanks,
Stefan

<html>
<body>

host.ioBrokerGarage | 2021-05-14 15:57:31.353 | info | Restart adapter system.adapter.husq-automower.0 because enabled
-- | -- | -- | --
host.ioBrokerGarage | 2021-05-14 15:57:31.350 | error | instance system.adapter.husq-automower.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
husq-automower.0 | 2021-05-14 15:57:31.022 | info | (26493) Logged on. Checking for mowers.
husq-automower.0 | 2021-05-14 15:57:30.721 | warn | (26493) State "husq-automower.0.info.connection" has no existing object, this might lead to an error in future versions
husq-automower.0 | 2021-05-14 15:57:30.652 | warn | (26493) Terminated (UNCAUGHT_EXCEPTION): Without reason
husq-automower.0 | 2021-05-14 15:57:30.648 | info | (26493) terminating
husq-automower.0 | 2021-05-14 15:57:30.645 | info | (26493) cleaned everything up...
husq-automower.0 | 2021-05-14 15:57:30.643 | info | (26493) Logged off.
husq-automower.0 | 2021-05-14 15:57:30.620 | warn | (26493) State "husq-automower.0.info.connection" has no existing object, this might lead to an error in future versions
husq-automower.0 | 2021-05-14 15:57:30.558 | error | (26493) Cannot read property 'val' of null
husq-automower.0 | 2021-05-14 15:57:30.556 | error | at processImmediate (internal/timers.js:463:21)
husq-automower.0 | 2021-05-14 15:57:30.556 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.husq-automower/main.js:1391:49)
husq-automower.0 | 2021-05-14 15:57:30.556 | error | (26493) TypeError: Cannot read property 'val' of null
husq-automower.0 | 2021-05-14 15:57:30.551 | error | (26493) uncaught exception: Cannot read property 'val' of null
husq-automower.0 | 2021-05-14 15:57:30.225 | info | (26493) Logged off.
husq-automower.0 | 2021-05-14 15:57:30.101 | info | (26493) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.husq-automower, node: v14.16.1, js-controller: 3.2.16

</body>
</html>

**Comment by evanes68** [comment]
I had this and added the missing connection property in the objects, two other fields later and i have a new type of error:

2021-05-19 20:38:05.314  - debug: husq-automower.0 (9850) updateStatus started
2021-05-19 20:38:05.316  - debug: husq-automower.0 (9850) updateStatus typeof mobjMower: object
2021-05-19 20:38:05.325  - error: husq-automower.0 (9850) uncaught exception: mobjMower.getStatus is not a function
2021-05-19 20:38:05.331  - error: husq-automower.0 (9850) TypeError: mobjMower.getStatus is not a function
    at Timeout.updateStatus [as _onTimeout] (/opt/iobroker/node_modules/iobroker.husq-automower/main.js:991:15)
2021-05-19 20:38:05.332  - error: husq-automower.0 (9850) mobjMower.getStatus is not a function
